package com.yzx.entity;

// Generated 2016-12-10 22:32:57 by Hibernate Tools 3.4.0.CR1

/**
 * ArticleCategory generated by hbm2java
 */
public class ArticleCategory implements java.io.Serializable {

	private String PId;
	private String categoryId;
	private String categoryName;
	private String categoryDesc;
	private byte articleNode;

	public ArticleCategory() {
	}

	public ArticleCategory(String PId, String categoryId, String categoryName,
			byte articleNode) {
		this.PId = PId;
		this.categoryId = categoryId;
		this.categoryName = categoryName;
		this.articleNode = articleNode;
	}

	public ArticleCategory(String PId, String categoryId, String categoryName,
			String categoryDesc, byte articleNode) {
		this.PId = PId;
		this.categoryId = categoryId;
		this.categoryName = categoryName;
		this.categoryDesc = categoryDesc;
		this.articleNode = articleNode;
	}

	public String getPId() {
		return this.PId;
	}

	public void setPId(String PId) {
		this.PId = PId;
	}

	public String getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(String categoryId) {
		this.categoryId = categoryId;
	}

	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	public String getCategoryDesc() {
		return this.categoryDesc;
	}

	public void setCategoryDesc(String categoryDesc) {
		this.categoryDesc = categoryDesc;
	}

	public byte getArticleNode() {
		return this.articleNode;
	}

	public void setArticleNode(byte articleNode) {
		this.articleNode = articleNode;
	}

}
