package com.yzx.entity;

// Generated 2016-12-10 22:32:57 by Hibernate Tools 3.4.0.CR1

/**
 * ArticleContent generated by hbm2java
 */
public class ArticleContent implements java.io.Serializable {

	private String articleId;
	private String articleContent;

	public ArticleContent() {
	}

	public ArticleContent(String articleId) {
		this.articleId = articleId;
	}

	public ArticleContent(String articleId, String articleContent) {
		this.articleId = articleId;
		this.articleContent = articleContent;
	}

	public String getArticleId() {
		return this.articleId;
	}

	public void setArticleId(String articleId) {
		this.articleId = articleId;
	}

	public String getArticleContent() {
		return this.articleContent;
	}

	public void setArticleContent(String articleContent) {
		this.articleContent = articleContent;
	}

}
