package com.yzx.entity;

// Generated 2016-12-10 22:32:57 by Hibernate Tools 3.4.0.CR1

/**
 * Article generated by hbm2java
 */
public class Article implements java.io.Serializable {

	private String articleId;
	private String category;
	private String articleTitle;
	private int articleStatus;
	private int genTime;
	private String articleDescription;

	public Article() {
	}

	public Article(String articleId, String category, String articleTitle,
			int articleStatus, int genTime) {
		this.articleId = articleId;
		this.category = category;
		this.articleTitle = articleTitle;
		this.articleStatus = articleStatus;
		this.genTime = genTime;
	}

	public Article(String articleId, String category, String articleTitle,
			int articleStatus, int genTime, String articleDescription) {
		this.articleId = articleId;
		this.category = category;
		this.articleTitle = articleTitle;
		this.articleStatus = articleStatus;
		this.genTime = genTime;
		this.articleDescription = articleDescription;
	}

	public String getArticleId() {
		return this.articleId;
	}

	public void setArticleId(String articleId) {
		this.articleId = articleId;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public String getArticleTitle() {
		return this.articleTitle;
	}

	public void setArticleTitle(String articleTitle) {
		this.articleTitle = articleTitle;
	}

	public int getArticleStatus() {
		return this.articleStatus;
	}

	public void setArticleStatus(int articleStatus) {
		this.articleStatus = articleStatus;
	}

	public int getGenTime() {
		return this.genTime;
	}

	public void setGenTime(int genTime) {
		this.genTime = genTime;
	}

	public String getArticleDescription() {
		return this.articleDescription;
	}

	public void setArticleDescription(String articleDescription) {
		this.articleDescription = articleDescription;
	}

}
