package com.yzx.entity;

// Generated 2016-12-10 16:00:36 by Hibernate Tools 3.4.0.CR1

/**
 * Category generated by hbm2java
 */
public class Category implements java.io.Serializable {

	private int PId;
	private int categoryId;
	private String categoryName;
	private String categoryDesc;
	private byte articleNode;

	public Category() {
	}

	public Category(int PId, int categoryId, String categoryName, byte articleNode) {
		this.PId = PId;
		this.categoryId = categoryId;
		this.categoryName = categoryName;
		this.articleNode = articleNode;
	}

	public Category(int PId, int categoryId, String categoryName,
			String categoryDesc, byte articleNode) {
		this.PId = PId;
		this.categoryId = categoryId;
		this.categoryName = categoryName;
		this.categoryDesc = categoryDesc;
		this.articleNode = articleNode;
	}

	public int getPId() {
		return this.PId;
	}

	public void setPId(int PId) {
		this.PId = PId;
	}

	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	public String getCategoryDesc() {
		return this.categoryDesc;
	}

	public void setCategoryDesc(String categoryDesc) {
		this.categoryDesc = categoryDesc;
	}

	public byte getArticleNode() {
		return this.articleNode;
	}

	public void setArticleNode(byte articleNode) {
		this.articleNode = articleNode;
	}

}
